- hosts: web
  remote_user: root
  become: yes
  tasks:

  - name: Install Apache
    yum: 
      name: httpd
      state: present

  - name: Remove Apache
    yum:
      name: httpd
      state: removed

     