---
# tasks file for mysql-challange
- name: Install DB
  yum:
    name: "{{ db_server }}"
    state: installed
  notify: 
  - Start DB  
- name: Display DB installed
  debug:
    msg: "{{ db_server }}"
